apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "photoprism.fullname" . }}-mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: default
