{{- if .Values.persistence.enabled }}
{{- range $name, $pvc := .Values.persistence }}
{{- if $pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "photoprism.fullname" $ }}-{{ $name }}
spec:
  accessModes: {{ toYaml $pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ $pvc.size }}
  {{- if $pvc.storageClass }}
  storageClassName: "{{ $pvc.storageClass }}"
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
