apiVersion: v1
kind: Service
metadata:
  name: photoprism-samba
  labels:
    app: samba
spec:
  selector:
    app: samba
  ports:
    - name: smb
      port: 445
      targetPort: 445
  type: ClusterIP