apiVersion: v1
kind: Service
metadata:
  name: photoprism-sftpgo
  namespace: photoprism
spec:
  selector:
    app: photoprism-sftpgo
  ports:
    - protocol: TCP
      port: 22
      targetPort: 2022
  type: LoadBalancer